-- Tabla Reportes para el formulario de reporte estudiantil
CREATE TABLE IF NOT EXISTS Reportes (
  Id_Reporte INT AUTO_INCREMENT PRIMARY KEY,
  Es_Anonimo TINYINT(1) NOT NULL DEFAULT 0,
  Nombre_Completo VARCHAR(255) NULL,
  Tipo_Documento VARCHAR(50) NULL,
  Numero_Documento VARCHAR(50) NULL,
  Fecha_Nacimiento DATE NULL,
  Edad INT NULL,
  Genero VARCHAR(50) NULL,
  Estado_Civil VARCHAR(50) NULL,
  Email VARCHAR(255) NULL,
  Telefono VARCHAR(50) NULL,
  Direccion VARCHAR(255) NULL,
  Ocupacion VARCHAR(100) NULL,
  EPS VARCHAR(100) NULL,
  Historial_Medico TEXT NULL,
  Condicion_Especial TEXT NULL,
  Grado_Cargo VARCHAR(100) NULL,
  Institucion VARCHAR(255) NULL,
  Contacto_Emergencia VARCHAR(255) NULL,
  Telefono_Emergencia VARCHAR(50) NULL,
  Descripcion LONGTEXT NOT NULL,
  Evidencia LONGTEXT NULL,
  Contexto LONGTEXT NULL,
  Correo_Contacto VARCHAR(255) NULL,
  Estado_Reporte VARCHAR(50) NOT NULL DEFAULT 'Abierto',
  Prioridad VARCHAR(50) NOT NULL DEFAULT 'Media',
  Fecha_Registro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Fecha_Actualizacion DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  Usuario_Id INT NULL,
  INDEX idx_usuario (Usuario_Id),
  INDEX idx_estado (Estado_Reporte),
  INDEX idx_fecha (Fecha_Registro)
);
